name: Sync from Gitee to GitHub
on:
  schedule:
    - cron: '0 0/1 * * *'   # 每1小时检查一次Gitee更新
  workflow_dispatch:        # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    env:
      SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      
    steps:
      - name: Checkout GitHub repo
        uses: actions/checkout@v4
        with:
          ref: main
          # 关键：获取完整的提交历史
          fetch-depth: 0

      - name: Add Gitee to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan gitee.com >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts

      - name: Configure SSH for Gitee
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.GITEE_PRIVATE_KEY }}" > ~/.ssh/gitee_id_rsa
          chmod 600 ~/.ssh/gitee_id_rsa
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/gitee_id_rsa
          echo "SSH_AUTH_SOCK=$SSH_AUTH_SOCK" >> $GITHUB_ENV
          echo "SSH_AGENT_PID=$SSH_AGENT_PID" >> $GITHUB_ENV
          ssh -T git@gitee.com

      - name: Add Gitee remote
        run: git remote add gitee git@gitee.com:cp0612/stair-lighting.git

      - name: Pull from Gitee
        run: |
          git config user.name "Automation Bot"
          git config user.email "81408242@qq.com"
          git fetch gitee
          git merge gitee/master --allow-unrelated-histories

      - name: Push to GitHub
        run: |
          # 设置 SSH 方式推送
          git remote set-url origin git@github.com:cp0612/stair-lighting.git
          git push origin main
