name: Sync from Gitee to GitHub
on:
#  schedule:
#    - cron: '*/5 * * * *'   # 每 5 分钟检查一次 Gitee 更新
  workflow_dispatch:        # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub repo
        uses: actions/checkout@v4
        with:
          ref: main

      # 修复1：正确添加 known_hosts
      - name: Add Gitee to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan gitee.com >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts

      # 修复2：正确写入和加载私钥
      - name: Configure SSH for Gitee
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.GITEE_PRIVATE_KEY }}" > ~/.ssh/gitee_id_rsa
          chmod 600 ~/.ssh/gitee_id_rsa
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/gitee_id_rsa
          
          # 测试连接
          ssh -T git@gitee.com

      - name: Add Gitee remote
        run: git remote add gitee git@gitee.com:cp0612/stair-lighting.git

      - name: Pull from Gitee
        run: |
          git config user.name "Automation Bot"
          git config user.email "81408242@qq.com"
          git fetch gitee
          git merge gitee/master --allow-unrelated-histories

      - name: Push to GitHub
        run: git push origin main
