name: Sync from Gitee to GitHub
on:
#  schedule:
#    - cron: '*/5 * * * *'   # 每 5 分钟检查一次 Gitee 更新
  workflow_dispatch:        # 允许手动触发
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub repo
        uses: actions/checkout@v4
        with:
          ref: main

      # 关键修复：添加 SSH 主机密钥验证
      - name: Add Gitee to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan gitee.com >> ~/.ssh/known_hosts

      # 关键修复：在拉取前配置 SSH 密钥
      - name: Configure SSH for Gitee
        run: |
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          echo "${{ secrets.GITEE_PRIVATE_KEY }}" | ssh-add -
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock

      - name: Add Gitee remote
        run: git remote add gitee git@gitee.com:cp0612/stair-lighting.git

      - name: Pull from Gitee
        run: |
          git config user.name "Automation Bot"
          git config user.email "81408242@qq.com"
          git fetch gitee
          git merge gitee/master --allow-unrelated-histories

      - name: Push to GitHub
        run: git push origin main
