name: Sync from Gitee to GitHub
on:
  schedule:
    - cron: '*/5 * * * *'   # 每 5 分钟检查一次
  workflow_dispatch:        # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub repo
        uses: actions/checkout@v4
        with:
          ref: main
          # 关键修复：允许持久化认证信息
          persist-credentials: false  

      - name: Setup SSH keys and known_hosts
        run: |
          # 配置SSH目录
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          
          # 将私钥写入文件
          echo "${{ secrets.GITEE_PRIVATE_KEY }}" > ~/.ssh/gitee_key
          chmod 600 ~/.ssh/gitee_key
          
          # 添加Gitee到已知主机
          ssh-keyscan gitee.com >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts
          
          # 配置Git使用SSH密钥
          git config --global core.sshCommand "ssh -i ~/.ssh/gitee_key -o IdentitiesOnly=yes"

      - name: Add Gitee remote
        run: git remote add gitee git@gitee.com:cp0612/stair-lighting.git

      - name: Pull from Gitee
        run: |
          git config user.name "Automation Bot"
          git config user.email "81408242@qq.com"
          git fetch gitee
          # 注意：你的Gitee分支是master，GitHub是main
          git merge gitee/master --allow-unrelated-histories

      - name: Push to GitHub
        run: git push origin main
